import {
  Box,
  BrickWall,
  Circle,
  Check,
  CircleArrowRight,
  Clapperboard,
  Droplet,
  Egg,
  Expand,
  FlaskConical,
  Hammer,
  Lightbulb,
  LockKeyhole,
  Map,
  MessageCircle,
  Microscope,
  NotebookTabs,
  Package,
  Palette,
  PartyPopper,
  Pencil,
  Play,
  Recycle,
  RefreshCw,
  Ruler,
  Search,
  Settings,
  Shield,
  Sparkles,
  Star,
  Target,
  Trash2,
  TriangleAlert,
  Trophy,
  Truck,
  UnlockKeyhole,
  UsersRound,
  Volume2,
  VolumeX,
  Waves,
  X,
  type LucideIcon,
} from "lucide-react";

export type AppIconName =
  | "box" | "brick" | "bubbles" | "check" | "continue" | "movie" | "drop"
  | "egg" | "expand" | "flask" | "hammer" | "idea" | "lock" | "map" | "message"
  | "microscope" | "notebook" | "package" | "palette" | "party" | "pencil" | "play"
  | "recycle" | "refresh" | "ruler" | "search" | "settings" | "shield" | "sparkles"
  | "star" | "target" | "trash" | "warning" | "trophy" | "truck" | "unlock" | "users"
  | "volume" | "volume-off" | "waves" | "x";

const ICONS: Record<AppIconName, LucideIcon> = {
  box: Box,
  brick: BrickWall,
  bubbles: Circle,
  check: Check,
  continue: CircleArrowRight,
  movie: Clapperboard,
  drop: Droplet,
  egg: Egg,
  expand: Expand,
  flask: FlaskConical,
  hammer: Hammer,
  idea: Lightbulb,
  lock: LockKeyhole,
  map: Map,
  message: MessageCircle,
  microscope: Microscope,
  notebook: NotebookTabs,
  package: Package,
  palette: Palette,
  party: PartyPopper,
  pencil: Pencil,
  play: Play,
  recycle: Recycle,
  refresh: RefreshCw,
  ruler: Ruler,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trash: Trash2,
  warning: TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  unlock: UnlockKeyhole,
  users: UsersRound,
  volume: Volume2,
  "volume-off": VolumeX,
  waves: Waves,
  x: X,
};

export function AppIcon({ name, className, strokeWidth = 2 }: { name: AppIconName; className?: string; strokeWidth?: number }) {
  const Icon = ICONS[name];
  return <Icon className={`app-icon${className ? ` ${className}` : ""}`} aria-hidden="true" strokeWidth={strokeWidth} focusable="false" />;
}
